language: python

# Test on all versions
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"

# Install dependencies
install: pip install -r requirements.txt

# Run the tests
script: python manage.py test
